version: '3'

volumes:
  jenkins_home:
  devDeployment:
  masterDeployment:
  devConfig:
  masterConfig:
  psqlDevConfig:
  psqlMasterConfig:

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - devDeployment:/devDeployment
      - masterDeployment:/masterDeployment
      - jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
  wildflyDev:
    image: jboss/wildfly
    ports:
      - "8081:8080"
    volumes:
      - devDeployment:/opt/jboss/wildfly/standalone/deployments
      - devConfig:/opt/jboss/wildfly/standalone/configuration
  wildflyMaster:
    image: jboss/wildfly
    ports:
      - "8082:8080"
    volumes:
      - masterDeployment:/opt/jboss/wildfly/standalone/deployments
      - masterConfig:/opt/jboss/wildfly/standalone/configuration
  postgresMaster:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - psqlMasterConfig:/var/lib/postgresql/data
  postgresDev:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - psqlDevConfig:/var/lib/postgresql/data