version: '3.1'

volumes:
  jenkins_home:
  devDeployment:
  masterDeployment:
  devConfig:
  masterConfig:
  psqlDevConfig:
  psqlMasterConfig:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

services:
#JENKINS
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - devDeployment:/devDeployment
      - masterDeployment:/masterDeployment
      - jenkins_home:/var/jenkins_home

#ANALYSIS TOOLS
  #Sonar
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  #APPLICATION SERVERS
  wildflyDev:
    image: wildfly-admin
    ports:
      - "8081:8080"
      - "9991:9990"
    volumes:
      - devDeployment:/opt/jboss/wildfly/standalone/deployments
      - devConfig:/opt/jboss/wildfly/standalone/configuration
    links:
      - postgresDev:database
  wildflyMaster:
    image: wildfly-admin
    ports:
      - "8082:8080"
      - "9992:9990"
    volumes:
      - masterDeployment:/opt/jboss/wildfly/standalone/deployments
      - masterConfig:/opt/jboss/wildfly/standalone/configuration
    links:
      - postgresMaster:database

#DATABASES
  postgresMaster:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - psqlMasterConfig:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  postgresDev:
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - psqlDevConfig:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres